### ISSUE TITLE
UX issue with constant red alarm from CPULowAlarm

### ISSUE THREAD

**Issue by audvin** [widdix/aws-cf-templates#134]
TemplateID: `wordpress/wordpress-ha`
Region: `us-east-1`

As a user, it alarms me 🤓 to see a red ALARM in CloudWatch constantly when the alarm is for `CPULowAlarm`...which is a good thing. I know this is used to the autoscaling feature, but shouldn't there be another better way to trigger and control the scaling? The UX is troublesome, first it alarms me when I see it, but over time I've gotten used to seeing it which is the second problem, now I don't spot real alerts since there always an alert running...

Can this be improved?

**Comment by michaelwittig** [comment]
I'm not aware of a reasonable way to implement auto scaling without alarms. 

But, you may want to use alarm actions instead of checking them in the dashboard. have you looked at the parameters of the `operations/alert.yaml` template? You can subscribe to alarms via email or you can integrate them right into Slack with https://marbot.io

**Comment by audvin** [comment]
I created a PR example of how I solved this for my needs. https://github.com/widdix/aws-cf-templates/pull/135

**Comment by michaelwittig** [comment]
I commented on the PR

**Comment by michaelwittig** [comment]
https://aws.amazon.com/about-aws/whats-new/2017/11/hide-your-cloudwatch-alarms-that-you-use-for-auto-scaling-actions/
