### ISSUE TITLE
New "SubDomainName" Parameter Unable to Be Left Blank (for non-www DNS entry)

### ISSUE THREAD

**Issue by ILLUMINICE** [widdix/aws-cf-templates#139]
I think I may have found a small issue with the new "SubDomainName" parameter...

It seems that if you want to have your A-record entry just be domain.com (and not www.domain.com or some other sub-domain) this is not possible because this parameter is required. If you leave this field blank it creates an error during deployment and then a rollback.

I like that you've integrated Route 53 with the ability to create a zone, and I'm making use of this. But at the moment there seems to be no way to add an entry unless you use www or some other sub-domain. In my case I just need a simple domain.com (no www).

.....

On a semi-related topic, I do need to get www to work as well, but am not 100% sure how to do this yet. I think it needs to be added as an alias in CloudFront first. Then I should be able to use a rewrite rule in htaccess to just change the URL not to use the www by default.

~ Michael

**Comment by michaelwittig** [comment]
`SubDomainName` is required when `ParentZoneStack` is set, otherwise not considered.

DNS apex entry is not supported (e.g., domain.com).

Only subdomains (e.g., www.domain.com). The name `SubDomainName` tries to imply this. You have to tweak the template if you need it.

**Comment by ILLUMINICE** [comment]
Hi Michael,

Thanks for the quick response...

Yes, this is exactly what I found. I had to leave out the ParentZoneStack in order to temporarily solve this problem.

I really like that you've integrated the DNS zone into all the templates, but it would be more useful if it could create the entry with or without a sub-domain. When I saw this feature I assumed that by including the ParentZoneStack (and leaving the sub-domain field blank), that it would actually include the A-record entry as just "domain.com." Perhaps this is a feature worth including in this stack so everyone can make use of the ParentZoneStack.

You could also take this a step further and make it so that any sub-domains entered would be automatically added as aliases for the CloudFront distribution (I believe that's necessary for them to actually point to the site). This would make it easier to have both domain.com and www.domain.com function out of the box.

Whether you include this or not, it's what I need to setup on my end. Perhaps you'll want to add this to the template for everyone.

All my best!

~ Michael

**Comment by michaelwittig** [comment]
I get your point. I classified this as a feature request.

**Comment by ILLUMINICE** [comment]
Thanks Michael, I appreciate that! I'll keep an eye out for this feature in the future...

**Comment by michaelwittig** [comment]
refs 3d95f7a96511104c33ee93ca40fb34b7084ec3d2

keep in mind that this change is only available in a development branch and will become available with v7

**Comment by ILLUMINICE** [comment]
Hi Michael,

Thanks for including this feature!

Just to clarify, this update will enable you to include the ParentZoneStack parameter which will then automatically create an A-entry pointing to the CloudFront distribution using domain.com (without www). This would work so long as you leave the sub-domain parameter empty.

Is this correct?

Also, when do you expect v7 to become available?

Thank you again for making this useful edit.

All my best,

~ Michael

**Comment by michaelwittig** [comment]
Hi @ILLUMINICE 

1. the `DomainName` parameter has been removed
2. the `ParentZoneStack` parameter is now required. If you have an existing Route53 Zone, you can wrap it with the `vpc/zone-legacy.yaml` template into a zone stack. This way you can continue to use your existing Route 53 zones.
3. the `SubDomainName` parameter was renamed to `SubDomainNameWithDot`. You can set the value to `www.` and your zone stack contains `test.com`, you will end up with an entry like `www.test.com`. But you can also leave `SubDomainNameWithDot` blank and end up with `test.com` which was not possible before.

The reason for the breaking change is that we introduced zone stacks a few months before and now we have the same behaviour for all templates. (Only WordPress and static website supported Route 53 before).

v7 is mostly waiting for Amazon to release a NAT and ECS optimized version of Amazon Linux. According to AWS support, they are working on it. But as always, they don't tell us how long this will take. I'm eager to use the v7 templates myself, so I hope this will me a matter of a few weeks. Otherwise we may release without the AMIs from Amazon.

**Comment by ILLUMINICE** [comment]
@michaelwittig 

Thank you for explaining how this new configuration will work. I'm glad I asked you, as this is a bigger change than expected.

Your explanation here makes complete sense to me. It was clever to make use of the domain name already entered into the ParentZoneStack, so that we can eliminate the DomainName parameter in the WP stack. This also wrapped in my feature request rather nicely.

I had a feeling that you would eventually be making larger use of the ParentZoneStack, and so I made sure to use it when creating my zone. But it was smart to offer a way to wrap in stand-alone zones as well.

I'm very much looking forward to seeing this released. As for the new AMI, this is one aspect of these templates I have yet to closely examine. Up until this point I've been trusting the AMI's you've been selecting.

My thanks again for making these improvements!
