### ISSUE TITLE
Template Usage Questions

### ISSUE THREAD

**Issue by devotoare** [widdix/aws-cf-templates#30]
Sorry didn't know where else to ask this. Feel free to rebuke me.

I have a couple questions regarding the WordPress-HA template, but they may also apply to the VPC templates.

1. For the WordPress template it says edit `/root/config.sh` to edit plugins/themes. Is this done from the `wordpress-ha.json` file or from an instance after creation?
2. How can I allow one of my developers to connect directly to the database? I tried to enable their IP address to port 3306 in the DB security group, but they were still denied access. 
3. Will changes he makes to the primary database be replicated instantly to the slaves? I only ask because after launching I only saw 1 RDS instance at all.
4. How do I access the logs on the server (php errors/etc.)?

**Comment by michaelwittig** [comment]
Hi @devotoare 

let me answer your questions:

1. You need to edit the `wordpress-ha.json` file
2. The database runs in the private subnet. There is no direct way to access the database from the Internet (because of security). You can use a [Bastion Host](https://github.com/widdix/aws-cf-templates/tree/master/vpc#ssh-bastion-hostinstance) and than create a SSH Tunnel to connect with the RDS database
3. You have one RDS instance but in multi AZ mode. Which means that under the hood there are 
two EC2 instances but you can't see them. And yes, writes are replicated synchronously.
4. You can find them in CloudWatch Logs. We create Log Group for every stack and inside you find log files for all the running instances.

I hope this helps?

**Comment by devotoare** [comment]
@michaelwittig ,

Yes that helps a lot thank you.
