### ISSUE TITLE
Promotion to cfn-module (e.g. of elasticache-redis)

### ISSUE THREAD

**Issue by ambsw-technology** [widdix/aws-cf-templates#353]
Is there a criteria for moving a resource like `elasticache-redis` to `cnf-modules`?

We're working on our first CloudFormation stack and `cfn-modules` looks like a huge head start.  As part of our application, we need to implement Redis.  We could run it as an ECS service (using the `cfn-modules` template), but it seems like Elasticache is the better long-term solution.

Given that this template already exists, we're interested in understanding what it would need to be ready for `cfn-modules`.

**Comment by oanhnn** [comment]
@ambsw-technology 
I was make `elasticache-redis` module for my project.
You can use it until it available on `cfn-modules` by:
```
$ npm install --save https://github.com/aws-cfm/elasticache-redis.git
```

**Comment by michaelwittig** [comment]
The only requirement is that we have tests (see the test folder in any of the modules) and that we see value in the module because we pay for the testing infrastructure (elasticache-redis is valuable :)

We are also happy to link to modules outside the cfn-modules org.

We are also happy create (mentioned or unmentioned) sponsored templates/modules: https://github.com/widdix/aws-cf-templates#sponsor-a-feature-or-bug-fix

I'm closing this since the issue tracker is not about `cfn-modules`.
