### ISSUE TITLE
JSON version ?

### ISSUE THREAD

**Issue by ebuildy** [widdix/aws-cf-templates#41]
Hello guys, don't find anything about this, why there is JSON version of templates? This could be useful to work on it via AWS editor.

Thanks you,

Tom

**Comment by michaelwittig** [comment]
Hi @ebuildy 
what do you mean by JSON version?

If you mean `AWSTemplateFormatVersion: '2010-09-09'` than you can find more about it here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html

**Comment by ebuildy** [comment]
Usually I am using JSON with AWS Designer, but with YAML, the designer cannot load template, hence we cannot work on it.

**Comment by michaelwittig** [comment]
looks like the designer does not (yet) support yaml. It is officially support from CloudFormation since a few weeks. You can either convert them to JSON or wait until the designer support yaml. Thea reason why we switched from yaml to json can be found here: https://cloudonaut.io/aws-cloudformation-update-evaluation-yaml-cross-stack-references-simplified-substitution/

**Comment by ebuildy** [comment]
Ha didn't find this post, sorry.

Thanks you for your time, I will convert it, but you are right, YAML seems much better for this kind of content.
