### ISSUE TITLE
Request to extend the wordpress-ha template to include S3 + Virus Scanning

### ISSUE THREAD

**Issue by deejvince** [widdix/aws-cf-templates#43]
Hi,

The new solution for wordpress-ha (non immutable with EFS) is very cool.
however it omits using S3 for user uploads / handing over static object serving to S3.

I ask to add S3 to this template (port from older blog), for two things:
1) Relieve Apache/EFS from serving static content, handover static objects to S3 -> configure cloudfront to point to S3 for static content.
2) one major concern is allowing users to upload files, serving them without 1st scanning them. this can be incoporated with your Lambda function for scan triggered by Put object.

Thanks,
Lior

**Comment by michaelwittig** [comment]
Hi Lior,

we try to make the templates as simple as possible. The two points you suggest make sense but are not the easiest way. Point 1 is maybe not too important because we have a CDN (CloudFront) in front, so static files will most likely be served from the CDN.

If you want custom modifications we are happy to help. Find more information here https://widdix.net/
