### ISSUE TITLE
Updating Jenkins template

### ISSUE THREAD

**Issue by kunalfleethawks** [widdix/aws-cf-templates#577]
Hello Authors,

Currently I am using this template :
Jenkins 2: highly available Jenkins master and dynamic agents, a cloudonaut.io template 
I installed it on AWS few months back. How do I upgrade this template to latest one? 

Thanks
Kunal

**Comment by timharsch** [comment]
good question.   I've struggled with this too.   Seems the only good way is to tear down the whole jenkins stack and then startup a new one with the latest template.  This is why I'm still using v12.11.0 of the template.

I sometimes have been able to patch problems with the template by using the CloudFormation update template feature.  But with that I always make sure the agents are the only part of the template that are affected by my changes, because I don't want to relaunch my master node and lose my job definitions and such.

**Comment by michaelwittig** [comment]
There is no need to tear down a stack. You update the existing stack with the new template. To get the new template, I recommend to 
1. visit https://templates.cloudonaut.io/en/stable/jenkins/#installation-guide_1
2. click in the Launch Stack button
3. At the top, you will see the **Template URL**, e.g. https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates-releases-eu-west-1/stable/jenkins/jenkins2-ha-agents.yaml
4. Copy the Template Url and close the tab
5. Navigate to your existing stack, press the Update button, 
6. Choose Replace current template and paste the Template URL into the **Amazon S3 URL** field.

**WARNING** If you update from one major version to a newer one always read the Migration Guide to see if there are breaking changes. E.g., https://templates.cloudonaut.io/en/stable/migrate-v13/

As stated in the docs, there is one **Limitation**  "Stack updates only work if no agents are running. Scale to zero agents before you update the stack!" https://templates.cloudonaut.io/en/stable/jenkins/#limitations_1

@timharsch You will not lose any data. The job definitions are stored on  EFS.
